### ISSUE TITLE
Turn off canonical mode. 

### ISSUE THREAD

**Issue by satyamvats5** [BytesClub/chalk#3]
As , we are working in ~~**canonical mode**~~, so the inpur we are providing is processed line by line. It means that the input is processed only after the line is completed( when *\n* or *EOF* is found). But we want to process our input word by word. so we need to turn off the **~~canonical mode~~**.:thumbsup:

**Comment by RudraNilBasu** [comment]
Fixed in https://github.com/BytesClub/chalk/commit/230959967f416a7986a50ad20d3574da4d8151e8
