### ISSUE TITLE
Turn off ctrl-c and ctrl-z signals

### ISSUE THREAD

**Issue by satyamvats5** [BytesClub/chalk#7]
By,defauult ***```ctrl-c```*** sends a signal to the current process which causes it to terminate, amnd ***```ctrl-z```*** sends a signal ti current process which causes it to suspend. We need to turn off the sending of both the signals for proper functioning of our text viewer(text editor in original).

**Comment by RudraNilBasu** [comment]
Fixed: https://github.com/BytesClub/chalk/commit/942570111f90951ea6e8c9e06efc7ba114dea3b9
